name: Spotify Widget Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
            version: 8.6.6

    - name: Install dependencies
      run: pnpm i

    - name: Generate packages
      run: |
        pnpm package-linux
        pnpm package-mac
        pnpm package-win

    - name: Compress build output
      run: |
        zip -r spotify-widget-mac.zip out/spotify-widget-darwin-x64
        zip -r spotify-widget-win32.zip out/spotify-widget-win32-x64
        tar -czvf spotify-widget-linux.tar.gz out/spotify-widget-linux-x64

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Linux release asset
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: spotify-widget-linux.zip
        asset_name: spotify-widget-linux.zip
        asset_content_type: application/zip
    
    - name: Upload mac release asset
      id: upload-release-asset-mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: spotify-widget-mac.zip
        asset_name: spotify-widget-mac.zip
        asset_content_type: application/zip

    - name: Upload windows release asset
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: spotify-widget-win32.zip
        asset_name: spotify-widget-win32.zip
        asset_content_type: application/zip
